#include "xy_lsm6dso.h"
#include "xy_device_timing.h"
#include "xy_hal_sys.h"
#include <string.h>
static int ready(const xy_lsm6dso_t*d){return d&&d->initialized&&d->i2c_dev.base.initialized&&d->i2c_dev.i2c_handle;}
static xy_error_t wr(xy_lsm6dso_t*d,uint8_t r,uint8_t v){return xy_i2c_device_write_reg(&d->i2c_dev,r,&v,1);}
xy_error_t xy_lsm6dso_init(xy_lsm6dso_t*d,void*h){uint8_t id;xy_error_t e;if(!d||!h)return XY_DEVICE_INVALID_PARAM;memset(d,0,sizeof(*d));e=xy_i2c_device_init(&d->i2c_dev,h,XY_LSM6DSO_ADDR,1000);if(e!=XY_DEVICE_OK)return e;e=xy_i2c_device_read_reg(&d->i2c_dev,XY_LSM6DSO_REG_WHOAMI,&id,1);if(e==XY_DEVICE_OK&&id!=XY_LSM6DSO_WHOAMI)e=XY_DEVICE_NOT_FOUND;if(e==XY_DEVICE_OK)e=wr(d,XY_LSM6DSO_REG_CTRL3_C,1);if(e==XY_DEVICE_OK){xy_device_delay_ms(10);e=wr(d,XY_LSM6DSO_REG_CTRL4_C,0);}if(e==XY_DEVICE_OK)e=wr(d,XY_LSM6DSO_REG_CTRL1_XL,XY_LSM6DSO_CTRL1_XL_104HZ_2G);if(e==XY_DEVICE_OK)e=wr(d,XY_LSM6DSO_REG_CTRL2_G,XY_LSM6DSO_CTRL2_G_104HZ_250DPS);if(e!=XY_DEVICE_OK){memset(d,0,sizeof(*d));return e;}d->initialized=1;return XY_DEVICE_OK;}
xy_error_t xy_lsm6dso_deinit(xy_lsm6dso_t*d){xy_error_t e;if(!ready(d))return XY_DEVICE_INVALID_PARAM;e=wr(d,XY_LSM6DSO_REG_CTRL1_XL,0);if(e==XY_DEVICE_OK)e=wr(d,XY_LSM6DSO_REG_CTRL2_G,0);if(e!=XY_DEVICE_OK)return e;d->initialized=0;d->i2c_dev.base.initialized=0;d->i2c_dev.i2c_handle=NULL;return XY_DEVICE_OK;}
xy_error_t xy_lsm6dso_read(xy_lsm6dso_t*d,xy_lsm6dso_sample_t*s){uint8_t a[6],g[6];xy_lsm6dso_sample_t n;xy_error_t e;if(!ready(d)||!s)return XY_DEVICE_INVALID_PARAM;e=xy_i2c_device_read_reg(&d->i2c_dev,XY_LSM6DSO_REG_OUTX_L_XL,a,6);if(e!=XY_DEVICE_OK)return e;e=xy_i2c_device_read_reg(&d->i2c_dev,XY_LSM6DSO_REG_OUTX_L_G,g,6);if(e!=XY_DEVICE_OK)return e;n.accel_x=(int16_t)((uint16_t)a[0]|((uint16_t)a[1]<<8));n.accel_y=(int16_t)((uint16_t)a[2]|((uint16_t)a[3]<<8));n.accel_z=(int16_t)((uint16_t)a[4]|((uint16_t)a[5]<<8));n.gyro_x=(int16_t)((uint16_t)g[0]|((uint16_t)g[1]<<8));n.gyro_y=(int16_t)((uint16_t)g[2]|((uint16_t)g[3]<<8));n.gyro_z=(int16_t)((uint16_t)g[4]|((uint16_t)g[5]<<8));n.timestamp=xy_hal_sys_get_tick_count();*s=n;d->sample=n;return XY_DEVICE_OK;}
