#ifndef _BANK_CFG_H_
#define _BANK_CFG_H_

#ifdef __cplusplus
extern "C" {
#endif

#define BANK_CFG_SUPPORT_FUEL_GAUGE 0
#define BANK_CFG_USE_FUEL_GAUGE_VOLTAGE 0
#define BANK_CFG_USE_FUEL_GAUGE_CURRENT 0
#define BANK_CFG_USE_FUEL_GAUGE_SOC 0
#define BANK_CFG_USE_FUEL_GAUGE_SOH 0

/** Bank Related timer settings */
#define BANK_CFG_PROCESS_PERIOD 100 // ms
#define BANK_CFG_PROCESS_1S_CNT (1000 / BANK_CFG_PROCESS_PERIOD)
#define BANK_CFG_PROCESS_2S_CNT (2 * BANK_CFG_PROCESS_1S_CNT)
#define BANK_CFG_PROCESS_3S_CNT (3 * BANK_CFG_PROCESS_1S_CNT)
#define BANK_CFG_PROCESS_5S_CNT (5 * BANK_CFG_PROCESS_1S_CNT)
#define BANK_CFG_PROCESS_10S_CNT (10 * BANK_CFG_PROCESS_1S_CNT)
#define BANK_CFG_PROCESS_15S_CNT (15 * BANK_CFG_PROCESS_1S_CNT)

#define BANK_CFG_MSQ_MAX_NUM 8

#define BANK_CFG_RESUME_SOC_UPDATE_CNT_MAX (BANK_CFG_PROCESS_15S_CNT)

#define BANK_CFG_VBUS_DETECT_PERIOD 20 // mS
#define BANK_CFG_VBUS_DETECT_IN_COUNT (5)
#define BANK_CFG_VBUS_DETECT_OUT_COUNT (5)

/**
 * @brief Bank battery manufacturer support configuration.
 *
 */
#define BANK_CFG_BATT_MFG_DEFAULT (7) // Must map to @ref bank_batt_mfg_t
#define BANK_CFG_BATT_MFG_FULLRIVER_ENABLE (0)
#define BANK_CFG_BATT_MFG_PANASONIC_ENABLE (0)
#define BANK_CFG_BATT_MFG_LGC_ENABLE (0)
#define BANK_CFG_BATT_MFG_AUCOPO_ENABLE (0)
#define BANK_CFG_BATT_MFG_REMPUS_ENABLE (0)
#define BANK_CFG_BATT_MFG_DESAY_ENABLE (0)
#define BANK_CFG_BATT_MFG_ATL_ENABLE (1)
#define BANK_CFG_BATT_MFG_COSMX_ENABLE (0)
#define BANK_CFG_BATT_MFG_BYD_DAK_ENABLE (0)
#define BANK_CFG_BATT_MFG_MIC_ENABLE (0)
#define BANK_CFG_BATT_MFG_CPW_ENABLE (0)

/**
 * @brief Bank battery related table size configuration.
 *
 */
#define BANK_CFG_BATT_TEMP_BAND_MAX (3)
#define BANK_CFG_BATT_AGE_MAX (3)
#define BANK_CFG_BATT_SOC_LEVEL_SIZE (4)

#define BANK_CFG_BATT_AGE_THRESHOLD1 (14877000UL)
#define BANK_CFG_BATT_AGE_THRESHOLD2 (16580160UL)
#define BANK_CFG_BATT_AGE_THRESHOLD3 (16580161UL)

/**
 * @brief Bank battery voltage related values
 *
 */
#define BANK_CFG_DEFAULT_IDLE_PROTECT_MV (2750)
#define BANK_CFG_DEFAULT_IDLE_FLAT_MV (3000)
#define BANK_CFG_DEFAULT_IDLE_CRITICAL_MV (3430)
#define BANK_CFG_DEFAULT_LO_CHARGING_CRITICAL_MV (3480)
#define BANK_CFG_DEFAULT_HI_CHARGING_CRITICAL_MV (3640)
// Battery voltage rising threshold from pre-charge to fast charge.
#define BANK_CFG_DEFUALT_VOLT_LOWVZ (3000)
/** Battery voltage conversion formula from EE design in mV. */
#define BANK_CFG_ADC_TO_VOLTAGE(adc) (uint16_t)(((adc) * 5500) >> 12)


#define BANK_CFG_MAX_LO_CHRG_CURRENT_MA (520)
#define BANK_CFG_MAX_MID_CHRG_CURRENT_MA (1200)
#define BANK_CFG_MAX_HI_CHRG_CURRENT_MA (2000)
#define BANK_CFG_PRE_CHRG_TIMEOUT (3600 * 2)
#define BANK_CFG_LO_CHRG_TIMEOUT (3600 * 5)
#define BANK_CFG_HI_CHRG_TIMEOUT (3600 * 2)
#define BANK_CFG_SHORT_CHRG_TIMEOUT (3600 * 1)

/**
 * @brief Bank battery temperature limit configuration.
 *
 */
#define BANK_CFG_BATT_EXT_NTC_TEMP_MAX_SPAN (127)
#define BANK_CFG_BATT_EXT_NTC_MIN_TEMP (0)
#define BANK_CFG_BATT_EXT_NTC_MAX_TEMP (60)
#define BANK_CFG_BATT_EXT_NTC_RECHARGE_TEMP (44)
#define BANK_CFG_START_HEATING_MIN_AMBIENT_TEMP (0)
#define BANK_CFG_START_HEATING_MAX_AMBIENT_TEMP (80)
#define BANK_CFG_BATT_MIN_AMBIENT_TEMP (-45)
#define BANK_CFG_BATT_MAX_AMBIENT_TEMP (128)

#define BANK_CFG_CHRG_CURRENT_STEP_SIZE (160)
#define BANK_CFG_CHRG_CURRENT_DEFAULT (120) // same as pre-chrg current
#define BANK_CFG_CHRG_CURRENT_MAX (2000)
#define BANK_CFG_CHRG_CURRENT_EXTR (3500)

#define BANK_CFG_CHRG_INPUT_LO_CURRENT (100)
#define BANK_CFG_CHRG_INPUT_DEFAULT_CURRENT (500)
#define BANK_CFG_CHRG_INPUT_MEDIUM_CURRENT (1000)
#define BANK_CFG_CHRG_INPUT_HIGH_CURRENT (1500)
#define BANK_CFG_CHRG_INPUT_MAX_CURRENT (2000)


/** @brief Critical level related values
 * Must be lower than the level defined by @ref bank_batt_level_low */
#define BANK_CFG_DEFAULT_IDLE_CRITICAL_LEVEL (5)
#define BANK_CFG_DEFAULT_CHRG_CRITICAL_LEVEL (7)

/**Bank unlimited control, only for special FW. */
#define BANK_CFG_NOT_TEMP_LIMIT 0
#define BANK_CFG_CHRG_NO_CURRENT_LIMIT 0

/**
 * @brief Bank log profile wrapp.
 *
 */
/** Bank Charge start reason index wrap*/
#define BANK_CFG_CHRG_START_REASON_INSERTION (0)
#define BANK_CFG_CHRG_START_REASON_USER (1)
#define BANK_CFG_CHRG_START_REASON_COMMAND (2)
#define BANK_CFG_CHRG_START_REASON_HEATING_OFF (3)
#define BANK_CFG_CHRG_START_REASON_UNKNOWN (4)

/** Bank Charge stop reason index wrap*/
#define BANK_CFG_CHRG_STOP_REASON_COMPLETED (0)
#define BANK_CFG_CHRG_STOP_REASON_USER (1)
#define BANK_CFG_CHRG_STOP_REASON_OVERHEAT (2)
#define BANK_CFG_CHRG_STOP_REASON_VOR (3)
#define BANK_CFG_CHRG_STOP_REASON_HARD_FAULT (4)
#define BANK_CFG_CHRG_STOP_REASON_TIMEOUT (5)
#define BANK_CFG_CHRG_STOP_REASON_CHIPFAULT (6)
#define BANK_CFG_CHRG_STOP_REASON_COLD_TEMP (7)
#define BANK_CFG_CHRG_STOP_REASON_HEATING (8)
#define BANK_CFG_CHRG_STOP_REASON_COMMAND (9)
#define BANK_CFG_CHRG_STOP_REASON_EXTRACTION (10)
#define BANK_CFG_CHRG_STOP_REASON_UNKNOWN (11)

/** Battery level wrap */
#define BANK_CFG_BATT_LEVEL_UNKNOWN (0)
#define BANK_CFG_BATT_LEVEL_FLAT (0)
#define BANK_CFG_BATT_LEVEL_CRITICAL (1)
#define BANK_CFG_BATT_LEVEL_2_LAST_EXP (2)
#define BANK_CFG_BATT_LEVEL_LOW (2)
#define BANK_CFG_BATT_LEVEL_MEDIUM (3)
#define BANK_CFG_BATT_LEVEL_HIGH (4)
#define BANK_CFG_BATT_LEVEL_FULL (5)
/** Battery UI level wrap */
#define BANK_CFG_BATT_UI_LEVEL_

#define BANK_CFG_CHRG_CABLE_IN (1)
#define BANK_CFG_CHRG_CABLE_OUT (2)
#define BANK_CFG_CHRG_CABLE_DETECT (1)

#define BANK_CFG_CHRG_COM_DISCONNECTED (0)
#define BANK_CFG_CHRG_COM_DETECTED (1)
#define BANK_CFG_CHRG_COM_CONNECTED (2)

#define BANK_CFG_CHRG_SOURCE_DCP_2050MA (0)
#define BANK_CFG_CHRG_SOURCE_SDP_500MA (1)
#define BANK_CFG_CHRG_SOURCE_SDP_100MA (2)
#define BANK_CFG_CHRG_SOURCE_CDP_DEFAULT_2050MA (3)
#define BANK_CFG_CHRG_SOURCE_CDP_AUDIO_500MA (4)
#define BANK_CFG_CHRG_SOURCE_CDP_MEDIUM_1500MA (5)
#define BANK_CFG_CHRG_SOURCE_CDP_HIGH_2050MA (6)
#define BANK_CFG_CHRG_SOURCE_SDP_SCP_DOCK_2050MA (7)
#define BANK_CFG_CHRG_SOURCE_NSA_1000MA (8)
#define BANK_CFG_CHRG_SOURCE_NSA_2000MA (9)
#define BANK_CFG_CHRG_SOURCE_NSA_2100MA (10)
#define BANK_CFG_CHRG_SOURCE_NSA_2400MA (11)
#define BANK_CFG_CHRG_SOURCE_UNKNOWN_500MA (12)

#define BANK_CFG_CHRG_SOURCE_DETECT_RETRY_MAX (5)
#define BANK_CFG_CHRG_SOURCE_DETECT_TIMEOUT (10)

#ifdef __cplusplus
}
#endif

#endif /* _BANK_CFG_H_ */