#include "xy_adxl362.h"
#include "xy_hal_sys.h"
#include <string.h>
static int ready(const xy_adxl362_t*d){return d&&d->initialized&&d->spi_dev.base.initialized&&d->spi_dev.spi_handle;}
static xy_error_t reg_write(xy_adxl362_t*d,uint8_t r,uint8_t v){uint8_t tx[3]={XY_ADXL362_CMD_WRITE,r,v},rx[3];return xy_spi_device_transfer(&d->spi_dev,tx,rx,3);}
static xy_error_t reg_read(xy_adxl362_t*d,uint8_t r,uint8_t*b,size_t n){uint8_t tx[256]={XY_ADXL362_CMD_READ,r},rx[256];xy_error_t e=xy_spi_device_transfer(&d->spi_dev,tx,rx,n+2);if(e==XY_DEVICE_OK)memcpy(b,&rx[2],n);return e;}
xy_error_t xy_adxl362_init(xy_adxl362_t*d,void*h,void*cs){uint8_t id;xy_error_t e;if(!d||!h||!cs)return XY_DEVICE_INVALID_PARAM;memset(d,0,sizeof(*d));e=xy_spi_device_init(&d->spi_dev,h,cs,1000000U,0U);if(e!=XY_DEVICE_OK)return e;e=reg_read(d,XY_ADXL362_REG_DEVID_AD,&id,1);if(e==XY_DEVICE_OK&&id!=XY_ADXL362_DEVID_AD)e=XY_DEVICE_NOT_FOUND;if(e==XY_DEVICE_OK)e=reg_write(d,XY_ADXL362_REG_FILTER_CTL,XY_ADXL362_FILTER_100HZ_2G);if(e==XY_DEVICE_OK)e=reg_write(d,XY_ADXL362_REG_POWER_CTL,XY_ADXL362_MEASUREMENT);if(e!=XY_DEVICE_OK){memset(d,0,sizeof(*d));return e;}d->initialized=1;return XY_DEVICE_OK;}
xy_error_t xy_adxl362_deinit(xy_adxl362_t*d){xy_error_t e;if(!ready(d))return XY_DEVICE_INVALID_PARAM;e=reg_write(d,XY_ADXL362_REG_POWER_CTL,XY_ADXL362_STANDBY);if(e!=XY_DEVICE_OK)return e;d->initialized=0;d->spi_dev.base.initialized=0;d->spi_dev.spi_handle=NULL;return XY_DEVICE_OK;}
xy_error_t xy_adxl362_read(xy_adxl362_t*d,xy_adxl362_sample_t*s){uint8_t b[6];xy_adxl362_sample_t n;xy_error_t e;if(!ready(d)||!s)return XY_DEVICE_INVALID_PARAM;e=reg_read(d,XY_ADXL362_REG_XDATA,b,6);if(e!=XY_DEVICE_OK)return e;n.raw_x=(int16_t)(((uint16_t)b[0]|((uint16_t)b[1]<<8))&0x0fff);n.raw_y=(int16_t)(((uint16_t)b[2]|((uint16_t)b[3]<<8))&0x0fff);n.raw_z=(int16_t)(((uint16_t)b[4]|((uint16_t)b[5]<<8))&0x0fff);if(n.raw_x&0x800)n.raw_x|=(int16_t)0xf000;if(n.raw_y&0x800)n.raw_y|=(int16_t)0xf000;if(n.raw_z&0x800)n.raw_z|=(int16_t)0xf000;n.timestamp=xy_hal_sys_get_tick_count();*s=n;d->sample=n;return XY_DEVICE_OK;}
