#include "xy_lsm9ds1.h"
#include "xy_device_timing.h"
#include "xy_hal_sys.h"
#include <string.h>
static int ready(const xy_lsm9ds1_t*d){return d&&d->initialized&&d->imu.base.initialized&&d->imu.i2c_handle&&d->mag.base.initialized&&d->mag.i2c_handle;}
static xy_error_t w(xy_i2c_device_t*d,uint8_t r,uint8_t v){return xy_i2c_device_write_reg(d,r,&v,1);}
xy_error_t xy_lsm9ds1_init(xy_lsm9ds1_t*d,void*h){uint8_t i,m;xy_error_t e;if(!d||!h)return XY_DEVICE_INVALID_PARAM;memset(d,0,sizeof(*d));e=xy_i2c_device_init(&d->imu,h,XY_LSM9DS1_IMU_ADDR,1000);if(e!=0){memset(d,0,sizeof(*d));return e;}e=xy_i2c_device_init(&d->mag,h,XY_LSM9DS1_MAG_ADDR,1000);if(e!=0){memset(d,0,sizeof(*d));return e;}e=xy_i2c_device_read_reg(&d->imu,15,&i,1);if(e==0&&i!=XY_LSM9DS1_IMU_WHOAMI)e=XY_DEVICE_NOT_FOUND;if(e==0)e=xy_i2c_device_read_reg(&d->mag,15,&m,1);if(e==0&&m!=XY_LSM9DS1_MAG_WHOAMI)e=XY_DEVICE_NOT_FOUND;if(e==0)e=w(&d->imu,XY_LSM9DS1_REG_CTRL3_C,1);if(e==0){xy_device_delay_ms(10);e=w(&d->imu,XY_LSM9DS1_REG_CTRL1_XL,XY_LSM9DS1_CTRL1_XL_104HZ_2G);}if(e==0)e=w(&d->imu,XY_LSM9DS1_REG_CTRL2_G,XY_LSM9DS1_CTRL2_G_104HZ_250DPS);if(e==0)e=w(&d->mag,XY_LSM9DS1_REG_CTRL_REG1_M,XY_LSM9DS1_CTRL1_M_10HZ_HIGH_POWER);if(e!=0){memset(d,0,sizeof(*d));return e;}d->initialized=1;return 0;}
xy_error_t xy_lsm9ds1_deinit(xy_lsm9ds1_t*d){xy_error_t e;if(!ready(d))return XY_DEVICE_INVALID_PARAM;e=w(&d->imu,XY_LSM9DS1_REG_CTRL1_XL,0);if(e==0)e=w(&d->imu,XY_LSM9DS1_REG_CTRL2_G,0);if(e==0)e=w(&d->mag,XY_LSM9DS1_REG_CTRL_REG1_M,0);if(e!=0)return e;d->initialized=0;d->imu.base.initialized=0;d->mag.base.initialized=0;d->imu.i2c_handle=NULL;d->mag.i2c_handle=NULL;return 0;}
xy_error_t xy_lsm9ds1_read(xy_lsm9ds1_t*d,xy_lsm9ds1_sample_t*s){uint8_t a[6],g[6],m[6];xy_lsm9ds1_sample_t n;xy_error_t e;if(!ready(d)||!s)return XY_DEVICE_INVALID_PARAM;e=xy_i2c_device_read_reg(&d->imu,40,a,6);if(e!=0)return e;e=xy_i2c_device_read_reg(&d->imu,34,g,6);if(e!=0)return e;e=xy_i2c_device_read_reg(&d->mag,40,m,6);if(e!=0)return e;n.accel_x=(int16_t)(a[0]|a[1]<<8);n.accel_y=(int16_t)(a[2]|a[3]<<8);n.accel_z=(int16_t)(a[4]|a[5]<<8);n.gyro_x=(int16_t)(g[0]|g[1]<<8);n.gyro_y=(int16_t)(g[2]|g[3]<<8);n.gyro_z=(int16_t)(g[4]|g[5]<<8);n.mag_x=(int16_t)(m[0]|m[1]<<8);n.mag_y=(int16_t)(m[2]|m[3]<<8);n.mag_z=(int16_t)(m[4]|m[5]<<8);n.timestamp=xy_hal_sys_get_tick_count();*s=n;d->sample=n;return 0;}
