#!/bin/bash

# XinYi 组件重组 - 代码引用路径更新指南

echo "=== 需要更新 #include 路径的文件列表 ==="
echo ""

echo "📁 影响的项目和示例："
echo ""

echo "1️⃣ examples/component_demo/demo_sensor.c"
echo "   需要更新的头文件："
echo "   - #include \"xy_sht30.h\" → 保持不变（使用 sensor 组件层）"
echo "   - #include \"xy_mpu6050.h\" → 保持不变（使用 sensor 组件层）"
echo "   - #include \"xy_bmp280.h\" → 保持不变（使用 sensor 组件层）"
echo "   - #include \"xy_ads1115.h\" → 保持不变（使用 sensor 组件层）"
echo ""

echo "2️⃣ examples/weather_station/main.c"
echo "   需要更新的头文件："
echo "   - #include \"xy_sht30.h\" → 保持不变（使用 sensor 组件层）"
echo "   - #include \"xy_mpu6050.h\" → 保持不变（使用 sensor 组件层）"
echo "   - #include \"xy_oled_ssd1306.h\" → 保持不变（使用 sensor 组件层）"
echo ""

echo "3️⃣ projects/Demo/main.c"
echo "   需要更新的头文件："
echo "   - #include \"xy_sht30.h\" → 保持不变（使用 sensor 组件层）"
echo "   - #include \"xy_eeprom_24xx.h\" → 需要确认是否需要直接访问驱动"
echo "   - #include \"xy_oled_ssd1306.h\" → 保持不变（使用 sensor 组件层）"
echo "   - #include \"xy_mpu6050.h\" → 保持不变（使用 sensor 组件层）"
echo "   - #include \"xy_bmp280.h\" → 保持不变（使用 sensor 组件层）"
echo ""

echo "4️⃣ projects/examples/smart_hygrometer/main.c"
echo "   需要更新的头文件："
echo "   - #include \"xy_sht30.h\" → 保持不变（使用 sensor 组件层）"
echo "   - #include \"xy_bmp280.h\" → 保持不变（使用 sensor 组件层）"
echo ""

echo "5️⃣ tests/test_device.c"
echo "   需要更新的头文件："
echo "   - #include \"xy_eeprom_24xx.h\" → #include \"drivers/storage/eeprom/24xx/xy_eeprom_24xx.h\""
echo "   - #include \"xy_oled_ssd1306.h\" → #include \"drivers/display/oled/ssd1306/xy_oled_ssd1306.h\""
echo ""

echo "6️⃣ components/ADDC/inc/xy_adc_ext.h"
echo "   需要更新的头文件："
echo "   - #include \"xy_ads1115.h\" → 保持不变（使用 sensor 组件层）"
echo ""

echo "7️⃣ components/sensor/inc/xy_dmp.h"
echo "   需要更新的头文件："
echo "   - #include \"xy_mpu6050.h\" → 保持不变（sensor组件内部引用）"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 架构说明："
echo ""
echo "  应用层"
echo "    ↓ 使用"
echo "  组件层 (components/sensor/)"
echo "    ↓ 使用"
echo "  驱动层 (components/drivers/sensor/)"
echo "    ↓ 使用"
echo "  HAL层 (components/hal/)"
echo ""

echo "大多数应用代码应该使用 **组件层** (components/sensor/)，"
echo "而不是直接访问驱动层 (components/drivers/)。"
echo ""
echo "只有在需要直接控制硬件时才使用驱动层。"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ 结论："
echo ""
echo "大部分文件 **不需要修改**，因为它们正确地使用了组件层。"
echo ""
echo "需要修改的文件："
echo "  - tests/test_device.c (如果要直接测试驱动)"
echo ""
echo "建议："
echo "  1. 保持现有的引用方式（使用组件层）"
echo "  2. 仅在必要时直接引用驱动层"
echo "  3. 更新 CMakeLists.txt 以确保头文件路径正确"
echo ""
