#!/usr/bin/env python3
"""
Kconfig Parser for XinYi Framework
Similar to Linux kernel's Kconfig system

Generates:
1. .config - Build configuration (like kernel .config)
2. autoconf.h - C header with CONFIG_* macros
3. config.cmake - CMake variables for build system
"""

import argparse
import os
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

class KconfigParser:
    def __init__(self):
        self.config: Dict[str, dict] = {}
        self.defaults: Dict[str, str] = {}
        self.dependencies: Dict[str, List[str]] = {}
        self.selects: Dict[str, List[str]] = {}
        
    def parse(self, kconfig_file: str) -> None:
        """Parse Kconfig file"""
        with open(kconfig_file, 'r') as f:
            content = f.read()
        
        # Parse config entries
        config_pattern = r'config\s+(\w+)'
        for match in re.finditer(config_pattern, content):
            config_name = match.group(1)
            start = match.end()
            
            # Find the block
            block_end = self._find_block_end(content, start)
            block = content[start:block_end]
            
            # Parse type
            type_match = re.search(r'\b(bool|string|int|hex)\b', block)
            config_type = type_match.group(1) if type_match else 'bool'
            
            # Parse default
            default_match = re.search(r'default\s+(.+?)(?:\n|$)', block)
            default_value = default_match.group(1).strip() if default_match else None
            
            # Parse depends on
            depends_match = re.search(r'depends on\s+(.+?)(?:\n|$)', block)
            depends_on = depends_match.group(1).strip() if depends_match else None
            
            # Parse select
            selects = re.findall(r'select\s+(\w+)', block)
            
            # Parse help
            help_match = re.search(r'help\s*\n((?:\s+.+\n)+)', block)
            help_text = help_match.group(1) if help_match else ""
            
            self.config[config_name] = {
                'type': config_type,
                'default': default_value,
                'depends_on': depends_on,
                'selects': selects,
                'help': help_text.strip()
            }
    
    def _find_block_end(self, content: str, start: int) -> int:
        """Find end of config block"""
        lines = content[start:].split('\n')
        end = start
        for i, line in enumerate(lines):
            if line.strip() and not line.startswith(' ') and not line.startswith('\t'):
                if not line.startswith('#'):
                    break
            end += len(line) + 1
        return end
    
    def resolve_dependencies(self) -> None:
        """Resolve config dependencies"""
        # Simple dependency resolution
        for name, cfg in self.config.items():
            if cfg['default'] and 'if' in cfg['default']:
                # Handle conditional defaults
                parts = cfg['default'].split('if')
                cfg['default'] = parts[0].strip()
                if len(parts) > 1:
                    cfg['depends_on'] = parts[1].strip()
    
    def _format_string_value(self, value: str) -> str:
        """Return a CMake/C-string friendly value without Kconfig quotes."""
        if value is None:
            return ""
        value = value.strip()
        if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
            value = value[1:-1]
        return value
    
    def generate_config(self, output_file: str) -> None:
        """Generate .config file"""
        with open(output_file, 'w') as f:
            f.write("# XinYi Framework Configuration\n")
            f.write("# Auto-generated - DO NOT EDIT\n\n")
            
            for name, cfg in sorted(self.config.items()):
                value = cfg['default'] if cfg['default'] else 'n'
                if cfg['type'] == 'bool':
                    value = 'y' if value and value != 'n' else 'n'
                elif cfg['type'] == 'string':
                    value = f'"{self._format_string_value(value)}"'
                f.write(f"CONFIG_{name}={value}\n")
    
    def generate_autoconf(self, output_file: str) -> None:
        """Generate autoconf.h"""
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        
        with open(output_file, 'w') as f:
            f.write("/**\n")
            f.write(" * @file autoconf.h\n")
            f.write(" * @brief Auto-generated configuration header\n")
            f.write(" * @note DO NOT EDIT - Generated by CMake\n")
            f.write(" */\n\n")
            f.write("#ifndef XY_AUTOCONF_H\n")
            f.write("#define XY_AUTOCONF_H\n\n")
            
            for name, cfg in sorted(self.config.items()):
                value = cfg['default'] if cfg['default'] else 'n'
                if cfg['type'] == 'bool':
                    enabled = 'y' in value.lower() if value else False
                    f.write(f"#define CONFIG_{name} {'1' if enabled else '0'}\n")
                elif cfg['type'] == 'string':
                    f.write(f'#define CONFIG_{name} "{self._format_string_value(value)}"\n')
                elif cfg['type'] == 'int':
                    try:
                        f.write(f"#define CONFIG_{name} {int(value)}\n")
                    except (ValueError, TypeError):
                        f.write(f"#define CONFIG_{name} 0\n")
                elif cfg['type'] == 'hex':
                    f.write(f"#define CONFIG_{name} 0x{value}\n")
            
            f.write("\n#endif /* XY_AUTOCONF_H */\n")
    
    def generate_cmake(self, output_file: str) -> None:
        """Generate config.cmake for CMake"""
        with open(output_file, 'w') as f:
            f.write("# XinYi Framework CMake Configuration\n")
            f.write("# Auto-generated - DO NOT EDIT\n\n")
            
            for name, cfg in sorted(self.config.items()):
                value = cfg['default'] if cfg['default'] else 'n'
                var_name = f"XY_{name}"
                
                if cfg['type'] == 'bool':
                    enabled = 'y' in value.lower() if value else False
                    f.write(f"set({var_name} {'ON' if enabled else 'OFF'})\n")
                elif cfg['type'] == 'string':
                    f.write(f"set({var_name} \"{self._format_string_value(value)}\")\n")
                else:
                    f.write(f"set({var_name} \"{value}\")\n")
                
                # Set environment variable for message()
                f.write(f"set(ENV{{{var_name}}} \"${{{var_name}}}\")\n")


def main():
    parser = argparse.ArgumentParser(description='Kconfig Parser for XinYi')
    parser.add_argument('--kconfig', required=True, help='Kconfig file path')
    parser.add_argument('--output', required=True, help='Output .config file')
    parser.add_argument('--autoconf', required=True, help='Output autoconf.h file')
    parser.add_argument('--cmake', required=True, help='Output config.cmake file')
    
    args = parser.parse_args()
    
    # Parse Kconfig
    kconfig = KconfigParser()
    kconfig.parse(args.kconfig)
    kconfig.resolve_dependencies()
    
    # Generate output files
    kconfig.generate_config(args.output)
    kconfig.generate_autoconf(args.autoconf)
    kconfig.generate_cmake(args.cmake)
    
    print(f"Generated: {args.output}")
    print(f"Generated: {args.autoconf}")
    print(f"Generated: {args.cmake}")


if __name__ == '__main__':
    main()
