#include "xy_apds9960.h"
#include "xy_hal_sys.h"
#include <string.h>
static int ready(const xy_apds9960_t*d){return d&&d->initialized&&d->i2c_dev.base.initialized&&d->i2c_dev.i2c_handle;}
static uint16_t le16(const uint8_t*b){return(uint16_t)b[0]|((uint16_t)b[1]<<8);}
xy_error_t xy_apds9960_init(xy_apds9960_t*d,void*h){uint8_t id,en=XY_APDS9960_ENABLE_PON_AEN_PEN_GEN;xy_error_t e;if(!d||!h)return XY_DEVICE_INVALID_PARAM;memset(d,0,sizeof(*d));e=xy_i2c_device_init(&d->i2c_dev,h,XY_APDS9960_ADDR,1000);if(e!=0)return e;e=xy_i2c_device_read_reg(&d->i2c_dev,XY_APDS9960_REG_ID,&id,1);if(e==0&&id!=0xABU&&id!=0x9CU)e=XY_DEVICE_NOT_FOUND;if(e==0)e=xy_i2c_device_write_reg(&d->i2c_dev,XY_APDS9960_REG_ENABLE,&en,1);if(e!=0){memset(d,0,sizeof(*d));return e;}d->initialized=1;return 0;}
xy_error_t xy_apds9960_deinit(xy_apds9960_t*d){uint8_t en=0;xy_error_t e;if(!ready(d))return XY_DEVICE_INVALID_PARAM;e=xy_i2c_device_write_reg(&d->i2c_dev,XY_APDS9960_REG_ENABLE,&en,1);if(e!=0)return e;d->initialized=0;d->i2c_dev.base.initialized=0;d->i2c_dev.i2c_handle=NULL;return 0;}
xy_error_t xy_apds9960_read_rgb(xy_apds9960_t*d,xy_apds9960_rgb_t*s){uint8_t b[8];xy_apds9960_rgb_t n;xy_error_t e;if(!ready(d)||!s)return XY_DEVICE_INVALID_PARAM;e=xy_i2c_device_read_reg(&d->i2c_dev,XY_APDS9960_REG_CDATAL,b,8);if(e!=0)return e;n.clear=le16(b);n.red=le16(b+2);n.green=le16(b+4);n.blue=le16(b+6);n.timestamp=xy_hal_sys_get_tick_count();*s=n;d->rgb=n;return 0;}
xy_error_t xy_apds9960_read_proximity(xy_apds9960_t*d,xy_apds9960_proximity_t*s){xy_apds9960_proximity_t n;xy_error_t e;if(!ready(d)||!s)return XY_DEVICE_INVALID_PARAM;e=xy_i2c_device_read_reg(&d->i2c_dev,XY_APDS9960_REG_PDATA,&n.proximity,1);if(e!=0)return e;n.timestamp=xy_hal_sys_get_tick_count();*s=n;d->proximity=n;return 0;}
xy_error_t xy_apds9960_read_gesture_fifo(xy_apds9960_t*d,xy_apds9960_gesture_fifo_t*s){uint8_t st,lvl;xy_apds9960_gesture_fifo_t n;xy_error_t e;if(!ready(d)||!s)return XY_DEVICE_INVALID_PARAM;memset(&n,0,sizeof(n));e=xy_i2c_device_read_reg(&d->i2c_dev,XY_APDS9960_REG_GSTATUS,&st,1);if(e!=0)return e;if(st&XY_APDS9960_GVALID){e=xy_i2c_device_read_reg(&d->i2c_dev,XY_APDS9960_REG_GFLVL,&lvl,1);if(e!=0)return e;if(lvl>32U)return XY_DEVICE_INVALID_PARAM;n.level=lvl;if(lvl){e=xy_i2c_device_read_reg(&d->i2c_dev,XY_APDS9960_REG_GFIFO_U,n.data,(size_t)lvl*4U);if(e!=0)return e;}}n.timestamp=xy_hal_sys_get_tick_count();*s=n;d->gesture=n;return 0;}
